### ISSUE TITLE
Strong/em conversions compliant with github/stackoverflows markdown implementations

### ISSUE THREAD

**Issue by herrstrietzel** [yne/md2dom#2]
Thanks for this great library!  

Frankly I'm not familiar with different markdown "flavors" or implementations.  
However, is there a way to map strong and italicized markdown notations as used in github or stackoverflow's  markdown parsers?  

So 

| render | code |  preview |
|--|--|--|
| strong | `**strong**` | **strong** |
| emphasis | `*emphasis*` | *emphasis* |

instead of (currently expected MD notations by m2dom)

| render | code |   
|--|--|
| strong | `*strong*` |
| emphasis | `_emphasis_` |

**Comment by yne** [comment]
shall `__double__` also generate a strong?

**Comment by herrstrietzel** [comment]
Thanks for your response!   
Seems like github also supports this syntax – so including `__double__` may be a good idea
